version: '2.13'
services:
  react-news-app:
    build:
      context: ./
    command: npm start
    ports:
      - "3000:3000"
    container_name: react-news-app
    stdin_open: true
    volumes:
       - ./:/usr/src